import type { AiManagerAction } from './aiActions'
import type { ZealthMessage } from './types'

function extractBullets(text: string): string[] {
  return text
    .split(/\n+/)
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => l.replace(/^[-*]\s+/, ''))
}

function formatList(items: string[]): string {
  return items.map((x) => `- ${x}`).join('\n')
}

function capitalizeSentences(text: string): string {
  return text
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/([.!?]\s+)([a-z])/g, (_, punct, letter) => punct + letter.toUpperCase())
    .replace(/^([a-z])/, (_, letter) => letter.toUpperCase())
}

function detectSoapSections(text: string): { label: string; content: string }[] | null {
  const lower = text.toLowerCase()
  const markers = [
    { key: 'subjective', label: 'Subjective' },
    { key: 'objective', label: 'Objective' },
    { key: 'assessment', label: 'Assessment' },
    { key: 'plan', label: 'Plan' },
  ]
  const found = markers.filter((m) => lower.includes(m.key))
  if (found.length < 2) return null

  const sections: { label: string; content: string }[] = []
  for (let i = 0; i < found.length; i++) {
    const start = lower.indexOf(found[i].key)
    const end =
      i + 1 < found.length ? lower.indexOf(found[i + 1].key) : text.length
    const slice = text.slice(start, end).replace(new RegExp(`^${found[i].key}\\s*:?`, 'i'), '').trim()
    if (slice) sections.push({ label: found[i].label, content: capitalizeSentences(slice) })
  }
  return sections.length ? sections : null
}

export function formatDictationTranscript(
  raw: string,
  _history: ZealthMessage[] = []
): string {
  const text = capitalizeSentences(raw)
  if (!text) {
    return 'No dictation text to process. Record or type notes, then try again.'
  }

  const soap = detectSoapSections(text)
  const timestamp = new Date().toLocaleString(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  })

  if (soap) {
    const body = soap.map((s) => `${s.label}:\n${s.content}`).join('\n\n')
    return [
      'DICTATION NOTE (SOAP)',
      `Recorded: ${timestamp}`,
      '',
      body,
      '',
      '— Review and edit before saving to the patient record.',
    ].join('\n')
  }

  const sentences = text.split(/(?<=[.!?])\s+/).filter(Boolean)
  const subjective = sentences.slice(0, Math.ceil(sentences.length / 2)).join(' ')
  const plan = sentences.slice(Math.ceil(sentences.length / 2)).join(' ')

  return [
    'DICTATION NOTE',
    `Recorded: ${timestamp}`,
    '',
    'Subjective:',
    subjective || text,
    '',
    'Objective:',
    '[Add examination findings]',
    '',
    'Assessment:',
    '[Add clinical assessment]',
    '',
    'Plan:',
    plan || '[Add treatment plan]',
    '',
    '— Review and edit before saving to the patient record.',
  ].join('\n')
}

export function generateActionOutput(
  action: AiManagerAction,
  input: string,
  history: ZealthMessage[] = []
): string {
  const text = input.trim()

  switch (action) {
    case 'dictation':
      return formatDictationTranscript(text, history)

    case 'report':
      return [
        'CLINICAL REPORT (DRAFT)',
        '',
        `Presenting concern: ${text || 'Mid-claim musculoskeletal review'}`,
        '',
        'Subjective: Patient reports reduced pain at rest (4/10). Aggravated by prolonged sitting.',
        'Objective: Lumbar flexion 70°. SLR negative. Mild paraspinal tenderness L4-L5.',
        'Assessment: Improving L4-L5 disc bulge with radicular symptoms.',
        'Plan: Continue exercise programme. Review in 2 weeks.',
        '',
        '— Generated by AI Manager. Clinician sign-off required.',
      ].join('\n')

    case 'summary':
      return generateZealthResponse(
        text ? `summarize: ${text}` : 'summarize recent clinical notes',
        history
      )

    case 'draft':
      return [
        'DRAFT NOTE',
        '',
        text ||
          'Follow-up appointment completed. Patient adherent to home programme. No new red flags. Continue current plan.',
        '',
        '— Edit and copy into your preferred documentation workflow.',
      ].join('\n')

    default:
      return generateZealthResponse(text, history)
  }
}

export function generateZealthResponse(userPrompt: string, history: ZealthMessage[]): string {
  const prompt = userPrompt.trim()
  if (!prompt) return 'Please type a message.'

  const lower = prompt.toLowerCase()

  if (lower.includes('summarize') || lower.includes('summary')) {
    const recentUserText = history
      .filter((m) => m.role === 'user')
      .slice(-5)
      .map((m) => m.content)
      .join('\n')
    const lines = extractBullets(recentUserText || prompt).slice(0, 5)
    return [
      'Here’s a short summary:',
      formatList(lines.length ? lines : [prompt.slice(0, 120) + (prompt.length > 120 ? '…' : '')]),
    ].join('\n')
  }

  if (lower.includes('plan') || lower.includes('roadmap') || lower.includes('steps')) {
    return [
      'Here’s a practical plan you can follow:',
      '- Clarify the goal and success criteria',
      '- List required data/inputs',
      '- Draft a simple first version',
      '- Test with a small sample',
      '- Iterate based on feedback',
      '',
      'If you share your exact goal, I can tailor this plan.',
    ].join('\n')
  }

  if (lower.includes('email') && lower.includes('template')) {
    return [
      'Here’s an email template you can use:',
      '',
      'Subject: [Your subject]',
      '',
      'Hi [Name],',
      '',
      'I hope you’re doing well. I’m reaching out about [topic].',
      'Could we [request] by [date/time]?',
      '',
      'Thanks,',
      '[Your Name]',
    ].join('\n')
  }

  if (lower.includes('meeting') || lower.includes('schedule')) {
    return [
      'To schedule this smoothly, please confirm:',
      '- Date range (e.g., next 7 days)',
      '- Preferred time window',
      '- Timezone',
      '- Meeting length',
      '',
      'Once you share these, I’ll propose a few slots.',
    ].join('\n')
  }

  // Default helpful assistant style response
  return [
    'Got it. Here’s a helpful response based on your prompt:',
    '',
    `“${prompt}”`,
    '',
    'Tell me what outcome you want (draft, checklist, explanation, or examples), and I’ll format it exactly that way.',
  ].join('\n')
}

